# Nome do workflow
name: Boris Prompts

# Eventos que acionarão este workflow: Quando houver um push no repositório
on:
  push:
    # Somente para arquivos com extensão .txt
    paths:
      - '**.txt'

# Definindo os jobs que serão executados
jobs:

  # Nome do job
  boris-check-prompt:
    
    # Definindo o sistema operacional onde o job será executado
    runs-on: ubuntu-latest
    
    # Etapas do job
    steps:

    # Etapa para obter o código do repositório
    - name: Check out code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    # Etapa para configurar o Python
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    # Cache
    - name: Cache Python dependencies
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('.github/workflows/prompt_review.yml') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    # Etapa para instalar as dependências necessárias
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install textstat

    # Capturando textos na variável $MY_VARIABLE
    - name: Set variable with git command output
      run: echo "MY_VARIABLE=$(git diff-tree --no-commit-id --name-status -r HEAD | grep -E '^[AM]\s' | cut -f2- | grep .txt | tr '\n' ' ')" >> $GITHUB_ENV
    
    # Visualizando textos da variável $MY_VARIABLE
    - name: Use the variable
      run: echo $MY_VARIABLE

    # Verificando seções obrigatórias no prompt
    - name: Checando as seções do Prompt
      run: python check_sections.py
      # Continuar mesmo se houver erro
      continue-on-error: True

    # Verificando o tamanho do prompt
    - name: Checando tamanho do Prompt
      run: python check_length.py
      # Continuar mesmo se houver erro
      continue-on-error: True

    # Verificando legibilidade do prompt
    - name: Checando legibilidade do prompt
      run: python check_readability.py
      # Continuar mesmo se houver erro
      continue-on-error: False
